export type Product = {
  sku: string;
  name: string;
  category: string;
  uom: string;
  abc: "A" | "B" | "C";
  stock: number;
  rop: number;
  warehouse: string;
  status: "active" | "low" | "critical" | "discontinued";
  cost: number;
  lastMovement: string;
  // Parametros reales extraídos del Excel Proyecto Nuclear
  demandaAnual: number;
  costoPedidoCp: number;
  costoMantenimientoH: number;
  leadTimeL: number;
};

export const products: Product[] = [
  {
    sku: "INS-LCH-01",
    name: "Leche Líquida",
    category: "Insumo",
    uom: "Litros",
    abc: "A",
    stock: 1255,
    rop: 2071,
    warehouse: "Bodega 12 (Materia Prima)",
    status: "active",
    cost: 2200,
    lastMovement: "Hace 10 min",
    demandaAnual: 254515,
    costoPedidoCp: 2200,
    costoMantenimientoH: 917.83,
    leadTimeL: 1,
  },
  {
    sku: "INS-AZU-01",
    name: "Azúcar",
    category: "Insumo",
    uom: "Kg",
    abc: "B",
    stock: 696,
    rop: 1644,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "low",
    cost: 3028.57,
    lastMovement: "Hace 1 hora",
    demandaAnual: 42275,
    costoPedidoCp: 3028.57,
    costoMantenimientoH: 288.91,
    leadTimeL: 7,
  },
  {
    sku: "INS-MAC-01",
    name: "Macadamia Simple",
    category: "Insumo",
    uom: "Gramos",
    abc: "C",
    stock: 13000,
    rop: 34017,
    warehouse: "Bodega 12 (Materia Prima)",
    status: "critical",
    cost: 90,
    lastMovement: "Ayer 15:30",
    demandaAnual: 677250,
    costoPedidoCp: 90,
    costoMantenimientoH: 4.08,
    leadTimeL: 7,
  },
  {
    sku: "INS-ENV-50",
    name: "Envase Cafequipe 50 GR",
    category: "Insumo",
    uom: "Unidades",
    abc: "A",
    stock: 87000,
    rop: 118174,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "active",
    cost: 90.08,
    lastMovement: "Hace 2 horas",
    demandaAnual: 561000,
    costoPedidoCp: 90.08,
    costoMantenimientoH: 3.39,
    leadTimeL: 40,
  },
  {
    sku: "PT-GAL-35",
    name: "Galleta de Café Display 35 GR x 8 UND",
    category: "Dulces",
    uom: "Display",
    abc: "A",
    stock: 778,
    rop: 1158,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "active",
    cost: 5900,
    lastMovement: "Hoy 08:15",
    demandaAnual: 31090,
    costoPedidoCp: 5900,
    costoMantenimientoH: 1499.12,
    leadTimeL: 7,
  },
  {
    sku: "PT-CQ-6X50",
    name: "Cafequipe 6x50 GR",
    category: "Dulces",
    uom: "Caja",
    abc: "B",
    stock: 1732,
    rop: 320,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "active",
    cost: 5328.25,
    lastMovement: "Hace 20 min",
    demandaAnual: 32134,
    costoPedidoCp: 5328.25,
    costoMantenimientoH: 1479.05,
    leadTimeL: 1,
  },
  {
    sku: "PT-CQ-250",
    name: "Cafequipe x 250 GR",
    category: "Dulces",
    uom: "Unidad",
    abc: "A",
    stock: 1251,
    rop: 346,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "active",
    cost: 3793.43,
    lastMovement: "Hoy 11:10",
    demandaAnual: 32002,
    costoPedidoCp: 3793.43,
    costoMantenimientoH: 801.16,
    leadTimeL: 1,
  },
  {
    sku: "PT-CUY-MAC",
    name: "Cuyabrito de Macadamia Cuadrado",
    category: "Dulces",
    uom: "Unidad",
    abc: "A",
    stock: 182,
    rop: 63,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "low",
    cost: 10125.07,
    lastMovement: "Ayer 17:00",
    demandaAnual: 8554,
    costoPedidoCp: 10125.07,
    costoMantenimientoH: 1050.23,
    leadTimeL: 1,
  },
  {
    sku: "PT-CQ-50",
    name: "Cafequipe x 50 GR",
    category: "Dulces",
    uom: "Unidad",
    abc: "A",
    stock: 1761,
    rop: 495,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "active",
    cost: 823.35,
    lastMovement: "Hace 5 min",
    demandaAnual: 53387,
    costoPedidoCp: 823.35,
    costoMantenimientoH: 63.67,
    leadTimeL: 1,
  },
  {
    sku: "PT-ARE-MAC125",
    name: "Arequipe de Macadamia x 125 GR",
    category: "Dulces",
    uom: "Unidad",
    abc: "B",
    stock: 351,
    rop: 946,
    warehouse: "Bodega 3 (Insumos/PT)",
    status: "critical",
    cost: 2464.48,
    lastMovement: "Hace 3 días",
    demandaAnual: 7980,
    costoPedidoCp: 2464.48,
    costoMantenimientoH: 89.69,
    leadTimeL: 1,
  },
];

export type Lot = {
  lot: string;
  sku: string;
  productName: string;
  qty: number;
  expiry: string; // ISO
  daysToExpiry: number;
  warehouse: string;
  bin: string;
  receivedAt: string;
};

export const lots: Lot[] = [
  {
    lot: "L-2031",
    sku: "PT-CQ-250",
    productName: "Cafequipe x 250 GR",
    qty: 480,
    expiry: "2026-05-17",
    daysToExpiry: 7,
    warehouse: "Bodega 3 (Insumos/PT)",
    bin: "C-12-03",
    receivedAt: "2025-08-12",
  },
  {
    lot: "L-7712",
    sku: "PT-GAL-35",
    productName: "Galleta de Café Display 35 GR",
    qty: 96,
    expiry: "2026-05-22",
    daysToExpiry: 12,
    warehouse: "Bodega 3 (Insumos/PT)",
    bin: "A-03-01",
    receivedAt: "2026-04-30",
  },
  {
    lot: "L-3340",
    sku: "INS-LCH-01",
    productName: "Leche Líquida",
    qty: 240,
    expiry: "2026-05-28",
    daysToExpiry: 18,
    warehouse: "Bodega 12 (Materia Prima)",
    bin: "B1-01-A",
    receivedAt: "2026-03-14",
  },
  {
    lot: "L-9921",
    sku: "PT-CUY-MAC",
    productName: "Cuyabrito de Macadamia Cuadrado",
    qty: 720,
    expiry: "2026-06-01",
    daysToExpiry: 22,
    warehouse: "Bodega 3 (Insumos/PT)",
    bin: "B2-04-02",
    receivedAt: "2026-05-01",
  },
  {
    lot: "L-4408",
    sku: "INS-AZU-01",
    productName: "Azúcar",
    qty: 44,
    expiry: "2026-06-12",
    daysToExpiry: 33,
    warehouse: "Bodega Insumos",
    bin: "B3-02-B",
    receivedAt: "2026-02-08",
  },
];
