export type Product = {
  sku: string;
  name: string;
  category: string;
  uom: string;
  abc: "A" | "B" | "C";
  stock: number;
  rop: number;
  warehouse: string;
  status: "active" | "low" | "critical" | "discontinued";
  cost: number;
  lastMovement: string;
};

export const products: Product[] = [
  {
    sku: "CQ-ARE-125",
    name: "Arequipe Sabor a Café x 125g",
    category: "Dulces",
    uom: "Unidad",
    abc: "A",
    stock: 1240,
    rop: 800,
    warehouse: "Armenia · Zona C",
    status: "active",
    cost: 4500,
    lastMovement: "Hace 12 min",
  },
  {
    sku: "CQ-GAL-100",
    name: "Galletas de Café x 100g",
    category: "Dulces",
    uom: "Caja",
    abc: "A",
    stock: 96,
    rop: 200,
    warehouse: "Armenia · Zona A",
    status: "low",
    cost: 3200,
    lastMovement: "Hace 38 min",
  },
  {
    sku: "CQ-CAF-01M",
    name: "Café Excelso Molido 500g",
    category: "Café Molido",
    uom: "Bolsa",
    abc: "A",
    stock: 240,
    rop: 150,
    warehouse: "Circasia · Bodega 1",
    status: "active",
    cost: 18500,
    lastMovement: "Hoy 09:14",
  },
  {
    sku: "CQ-CAF-02G",
    name: "Café Especial Grano 1kg",
    category: "Café en Grano",
    uom: "Paca",
    abc: "B",
    stock: 720,
    rop: 500,
    warehouse: "Circasia · Bodega 2",
    status: "active",
    cost: 36000,
    lastMovement: "Hoy 08:42",
  },
  {
    sku: "CQ-INS-AZU",
    name: "Azúcar Morena 50kg",
    category: "Insumos",
    uom: "Saco",
    abc: "B",
    stock: 24,
    rop: 80,
    warehouse: "Circasia · Bodega 3",
    status: "critical",
    cost: 155000,
    lastMovement: "Ayer 17:50",
  },
  {
    sku: "CQ-ARE-500",
    name: "Arequipe Tradicional 500g",
    category: "Dulces",
    uom: "Unidad",
    abc: "A",
    stock: 12,
    rop: 50,
    warehouse: "Bogotá · A-01",
    status: "critical",
    cost: 11000,
    lastMovement: "Hace 2 h",
  },
  {
    sku: "CQ-INS-EMP",
    name: "Empaque Primario Café",
    category: "Insumos",
    uom: "Millar",
    abc: "C",
    stock: 5,
    rop: 40,
    warehouse: "Armenia · Insumos",
    status: "critical",
    cost: 142000,
    lastMovement: "Ayer 14:21",
  },
  {
    sku: "CQ-BON-01",
    name: "Bombones de Café x 20",
    category: "Dulces",
    uom: "Caja",
    abc: "B",
    stock: 480,
    rop: 300,
    warehouse: "Bogotá · B-02",
    status: "active",
    cost: 19200,
    lastMovement: "Hoy 10:02",
  },
  {
    sku: "CQ-CAF-03M",
    name: "Café Tradicional Molido 250g",
    category: "Café Molido",
    uom: "Bolsa",
    abc: "A",
    stock: 1840,
    rop: 1200,
    warehouse: "Armenia · Zona B",
    status: "active",
    cost: 9500,
    lastMovement: "Hace 1 h",
  },
  {
    sku: "CQ-INS-CAJ",
    name: "Caja de Cartón Corrugado",
    category: "Insumos",
    uom: "Unidad",
    abc: "B",
    stock: 612,
    rop: 400,
    warehouse: "Circasia · Materiales",
    status: "active",
    cost: 890,
    lastMovement: "Hoy 11:18",
  },
  {
    sku: "CQ-END-PAN",
    name: "Panela Pulverizada 500g",
    category: "Endulzantes",
    uom: "Bolsa",
    abc: "C",
    stock: 320,
    rop: 200,
    warehouse: "Armenia · Zona C",
    status: "active",
    cost: 6500,
    lastMovement: "Hace 4 h",
  },
  {
    sku: "CQ-ANC-01",
    name: "Ancheta Puntos de Venta",
    category: "Dulces",
    uom: "Kit",
    abc: "A",
    stock: 88,
    rop: 120,
    warehouse: "Circasia · Promocional",
    status: "low",
    cost: 45000,
    lastMovement: "Hoy 07:30",
  },
];

export type Lot = {
  lot: string;
  sku: string;
  productName: string;
  qty: number;
  expiry: string; // ISO
  daysToExpiry: number;
  warehouse: string;
  bin: string;
  receivedAt: string;
};

export const lots: Lot[] = [
  {
    lot: "L-2031",
    sku: "CQ-ARE-125",
    productName: "Arequipe Sabor a Café x 125g",
    qty: 480,
    expiry: "2026-05-17",
    daysToExpiry: 7,
    warehouse: "Armenia",
    bin: "C-12-03",
    receivedAt: "2025-08-12",
  },
  {
    lot: "L-7712",
    sku: "CQ-GAL-100",
    productName: "Galletas de Café x 100g",
    qty: 96,
    expiry: "2026-05-22",
    daysToExpiry: 12,
    warehouse: "Armenia",
    bin: "A-03-01",
    receivedAt: "2026-04-30",
  },
  {
    lot: "L-3340",
    sku: "CQ-CAF-01M",
    productName: "Café Excelso Molido 500g",
    qty: 240,
    expiry: "2026-05-28",
    daysToExpiry: 18,
    warehouse: "Circasia",
    bin: "B1-01-A",
    receivedAt: "2026-03-14",
  },
  {
    lot: "L-9921",
    sku: "CQ-CAF-02G",
    productName: "Café Especial Grano 1kg",
    qty: 720,
    expiry: "2026-06-01",
    daysToExpiry: 22,
    warehouse: "Circasia",
    bin: "B2-04-02",
    receivedAt: "2026-05-01",
  },
  {
    lot: "L-4408",
    sku: "CQ-INS-AZU",
    productName: "Azúcar Morena 50kg",
    qty: 44,
    expiry: "2026-06-12",
    daysToExpiry: 33,
    warehouse: "Circasia",
    bin: "B3-02-B",
    receivedAt: "2026-02-08",
  },
  {
    lot: "L-1102",
    sku: "CQ-BON-01",
    productName: "Bombones de Café x 20",
    qty: 240,
    expiry: "2026-09-14",
    daysToExpiry: 127,
    warehouse: "Bogotá",
    bin: "B-02-04",
    receivedAt: "2026-04-10",
  },
  {
    lot: "L-8855",
    sku: "CQ-CAF-03M",
    productName: "Café Tradicional Molido 250g",
    qty: 1200,
    expiry: "2027-01-22",
    daysToExpiry: 257,
    warehouse: "Armenia",
    bin: "B-05-01",
    receivedAt: "2026-04-22",
  },
  {
    lot: "L-6601",
    sku: "CQ-ANC-01",
    productName: "Ancheta Puntos de Venta",
    qty: 12,
    expiry: "2026-07-30",
    daysToExpiry: 81,
    warehouse: "Circasia",
    bin: "PR-08-02",
    receivedAt: "2026-03-05",
  },
];
