/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppWarehousesRouteImport } from './routes/app.warehouses'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppShipmentsRouteImport } from './routes/app.shipments'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRolesRouteImport } from './routes/app.roles'
import { Route as AppReceiptsRouteImport } from './routes/app.receipts'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPickingRouteImport } from './routes/app.picking'
import { Route as AppManufacturingRouteImport } from './routes/app.manufacturing'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSaludRouteImport } from './routes/admin.salud'
import { Route as AdminPlanesRouteImport } from './routes/admin.planes'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminFacturacionRouteImport } from './routes/admin.facturacion'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AuthGoogleSuccessRouteImport } from './routes/auth.google.success'
import { Route as AuthGoogleErrorRouteImport } from './routes/auth.google.error'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppShipmentsRoute = AppShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPickingRoute = AppPickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => AppRoute,
} as any)
const AppManufacturingRoute = AppManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaludRoute = AdminSaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanesRoute = AdminPlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturacionRoute = AdminFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AuthGoogleSuccessRoute = AuthGoogleSuccessRouteImport.update({
  id: '/auth/google/success',
  path: '/auth/google/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleErrorRoute = AuthGoogleErrorRouteImport.update({
  id: '/auth/google/error',
  path: '/auth/google/error',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/salud': typeof AdminSaludRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/manufacturing': typeof AppManufacturingRoute
  '/app/picking': typeof AppPickingRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/stock': typeof AppStockRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/team': typeof AppTeamRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/google/error': typeof AuthGoogleErrorRoute
  '/auth/google/success': typeof AuthGoogleSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/salud': typeof AdminSaludRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/manufacturing': typeof AppManufacturingRoute
  '/app/picking': typeof AppPickingRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/stock': typeof AppStockRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/team': typeof AppTeamRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/auth/google/error': typeof AuthGoogleErrorRoute
  '/auth/google/success': typeof AuthGoogleSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/facturacion': typeof AdminFacturacionRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/planes': typeof AdminPlanesRoute
  '/admin/salud': typeof AdminSaludRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/billing': typeof AppBillingRoute
  '/app/manufacturing': typeof AppManufacturingRoute
  '/app/picking': typeof AppPickingRoute
  '/app/products': typeof AppProductsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/roles': typeof AppRolesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipments': typeof AppShipmentsRoute
  '/app/stock': typeof AppStockRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/team': typeof AppTeamRoute
  '/app/warehouses': typeof AppWarehousesRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/google/error': typeof AuthGoogleErrorRoute
  '/auth/google/success': typeof AuthGoogleSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/admin/auditoria'
    | '/admin/configuracion'
    | '/admin/empresas'
    | '/admin/facturacion'
    | '/admin/leads'
    | '/admin/planes'
    | '/admin/salud'
    | '/admin/usuarios'
    | '/app/analytics'
    | '/app/audit'
    | '/app/billing'
    | '/app/manufacturing'
    | '/app/picking'
    | '/app/products'
    | '/app/profile'
    | '/app/receipts'
    | '/app/roles'
    | '/app/settings'
    | '/app/shipments'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/team'
    | '/app/warehouses'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/'
    | '/app/'
    | '/auth/google/error'
    | '/auth/google/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/admin/auditoria'
    | '/admin/configuracion'
    | '/admin/empresas'
    | '/admin/facturacion'
    | '/admin/leads'
    | '/admin/planes'
    | '/admin/salud'
    | '/admin/usuarios'
    | '/app/analytics'
    | '/app/audit'
    | '/app/billing'
    | '/app/manufacturing'
    | '/app/picking'
    | '/app/products'
    | '/app/profile'
    | '/app/receipts'
    | '/app/roles'
    | '/app/settings'
    | '/app/shipments'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/team'
    | '/app/warehouses'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin'
    | '/app'
    | '/auth/google/error'
    | '/auth/google/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/admin/auditoria'
    | '/admin/configuracion'
    | '/admin/empresas'
    | '/admin/facturacion'
    | '/admin/leads'
    | '/admin/planes'
    | '/admin/salud'
    | '/admin/usuarios'
    | '/app/analytics'
    | '/app/audit'
    | '/app/billing'
    | '/app/manufacturing'
    | '/app/picking'
    | '/app/products'
    | '/app/profile'
    | '/app/receipts'
    | '/app/roles'
    | '/app/settings'
    | '/app/shipments'
    | '/app/stock'
    | '/app/suppliers'
    | '/app/team'
    | '/app/warehouses'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/terms'
    | '/admin/'
    | '/app/'
    | '/auth/google/error'
    | '/auth/google/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  AuthGoogleErrorRoute: typeof AuthGoogleErrorRoute
  AuthGoogleSuccessRoute: typeof AuthGoogleSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/warehouses': {
      id: '/app/warehouses'
      path: '/warehouses'
      fullPath: '/app/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shipments': {
      id: '/app/shipments'
      path: '/shipments'
      fullPath: '/app/shipments'
      preLoaderRoute: typeof AppShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/picking': {
      id: '/app/picking'
      path: '/picking'
      fullPath: '/app/picking'
      preLoaderRoute: typeof AppPickingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manufacturing': {
      id: '/app/manufacturing'
      path: '/manufacturing'
      fullPath: '/app/manufacturing'
      preLoaderRoute: typeof AppManufacturingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/salud': {
      id: '/admin/salud'
      path: '/salud'
      fullPath: '/admin/salud'
      preLoaderRoute: typeof AdminSaludRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planes': {
      id: '/admin/planes'
      path: '/planes'
      fullPath: '/admin/planes'
      preLoaderRoute: typeof AdminPlanesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturacion': {
      id: '/admin/facturacion'
      path: '/facturacion'
      fullPath: '/admin/facturacion'
      preLoaderRoute: typeof AdminFacturacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/google/success': {
      id: '/auth/google/success'
      path: '/auth/google/success'
      fullPath: '/auth/google/success'
      preLoaderRoute: typeof AuthGoogleSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/error': {
      id: '/auth/google/error'
      path: '/auth/google/error'
      fullPath: '/auth/google/error'
      preLoaderRoute: typeof AuthGoogleErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminFacturacionRoute: typeof AdminFacturacionRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminPlanesRoute: typeof AdminPlanesRoute
  AdminSaludRoute: typeof AdminSaludRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminFacturacionRoute: AdminFacturacionRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminPlanesRoute: AdminPlanesRoute,
  AdminSaludRoute: AdminSaludRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBillingRoute: typeof AppBillingRoute
  AppManufacturingRoute: typeof AppManufacturingRoute
  AppPickingRoute: typeof AppPickingRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShipmentsRoute: typeof AppShipmentsRoute
  AppStockRoute: typeof AppStockRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppBillingRoute: AppBillingRoute,
  AppManufacturingRoute: AppManufacturingRoute,
  AppPickingRoute: AppPickingRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShipmentsRoute: AppShipmentsRoute,
  AppStockRoute: AppStockRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTeamRoute: AppTeamRoute,
  AppWarehousesRoute: AppWarehousesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  AuthGoogleErrorRoute: AuthGoogleErrorRoute,
  AuthGoogleSuccessRoute: AuthGoogleSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
